apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "com.wowwee.revandroidsampleproject"
    compileSdk 36

    defaultConfig {
        applicationId "com.wowwee.revandroidsampleproject"
        minSdk 29
        targetSdk 36
        resValue "bool", "is_debug", "true"
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.9.24')
    implementation 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.12'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation project(':bluetoothrobotcontrollib_src')

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit:1.9.24'
    testImplementation 'org.robolectric:robolectric:4.13'
}
