apply plugin: 'com.android.library'

android {
    namespace "com.wowwee.bluetoothrobotcontrollib"
    compileSdk 36

    defaultConfig {
        minSdk 29
    }

    buildFeatures {
        buildConfig false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
}

